"https://www.ncbi.nlm.nih.gov/genomes/Genome2BE/genome2srv.cgi?action=download&orgn=%22Actinobacteria%20bacterium%22[orgn]&status=50|40|30|20&report=proks&group=--%20All%20Prokaryotes%20--&subgroup=--%20All%20Prokaryotes%20--&format=csv"

assembly_summary_file = ''
assembly_summary_header = ['assembly_accession',
                           'bioproject',
                           'biosample',
                           'wgs_master',
                           'refseq_category',
                           'taxid',
                           'species_taxid',
                           'organism_name',
                           'infraspecific_name',
                           'isolate',
                           'version_status',
                           'assembly_level',
                           'release_type',
                           'genome_rep',
                           'seq_rel_date',
                           'asm_name',
                           'submitter',
                           'gbrs_paired_asm',
                           'paired_asm_comp',
                           'ftp_path',
                           'excluded_from_refseq',
                           'relation_to_type_material']
